class MetasploitTasks < Thor
  include Core::Pro::ProjectScopedTask if defined?(::Core::Pro)


  namespace "dradis:plugins:metasploit"

  desc      "upload FILE", "upload Metasploit results in XML format"
  long_desc "This plugin expects an XML file generated by Metasploit using: db_export"\

  def upload(file_path)
    require 'config/environment'

    logger = Logger.new(STDOUT)
    logger.level = Logger::DEBUG

    unless File.exist?(file_path)
      $stderr.puts "** the file [#{file_path}] does not exist"
      exit(-1)
    end

    content_service = nil
    template_service = nil

    template_service = Dradis::Plugins::TemplateService.new(plugin: Dradis::Plugins::Metasploit)
    if defined?(Dradis::Pro)
    # Set project scope from the PROJECT_ID env variable:
      detect_and_set_project_scope
      content_service = Dradis::Pro::Plugins::ContentService.new(plugin: Dradis::Plugins::Metasploit)
    else
      content_service = Dradis::Plugins::ContentService.new(plugin: Dradis::Plugins::Metasploit)
    end

    importer = Dradis::Plugins::Metasploit::Importer.new(
                logger: logger,
       content_service: content_service, 
      template_service: template_service
    )
    
    importer.import(file: file_path)

    logger.close
  end

end
